/**
 * seed.js — Populates the database with pets and users.
 *
 * Usage:
 *   node seed.js
 *
 * Requires MONGODB_URI (or MONGO_URI) in .env
 * One pet is created per Cloudinary URL — images are assigned to their correct category.
 */

require("dotenv").config();
const mongoose = require("mongoose");
const bcrypt = require("bcrypt");

const Pets = require("./Schemas/petsSchemas");
const User = require("./Schemas/userSchemas");

const MONGO_URI = process.env.MONGODB_URI || process.env.MONGO_URI;
if (!MONGO_URI) {
  console.error("Missing MONGODB_URI (or MONGO_URI) in environment.");
  process.exit(1);
}

// ---------------------------------------------------------------------------
// DOGS — 8 from pets/ folder + 9 from categorized = 17 total
// ---------------------------------------------------------------------------
const dogs = [
  // ── pets/ folder ──────────────────────────────────────────────────────────
  {
    type: "Dog",
    breed: "Belgian Malinois",
    name: "סקאוט",
    adoptionStatus: "Available",
    height: 60,
    weight: 28,
    color: "Fawn with black mask",
    bio: "סקאוט הוא כלב עבודה לשעבר שעבד בגילוי ריחות. הוא אנרגטי, חכם ומסור, ומתאים לבית פעיל עם מאמנים מנוסים.",
    hypoallergenic: "No",
    dietaryRestrictions: "תזונה עשירה בחלבון",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584347/pets/sniffer-dog-covid-19.png_gyhqxl.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "Mixed Breed",
    name: "רנג'ר",
    adoptionStatus: "Available",
    height: 48,
    weight: 18,
    color: "Brown",
    bio: "רנג'ר הוא כלב מעורב שחולץ מהרחוב. הוא רגוע, נאמן ואוהב טיולים ארוכים עם בני משפחתו.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584346/pets/dogs-memory-learning-1600_x8c52z.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "Golden Retriever",
    name: "שמשון",
    adoptionStatus: "Available",
    height: 35,
    weight: 9,
    color: "Light Golden",
    bio: "שמשון הוא גור גולדן רטריבר מקסים שמוכן לבית קבוע. הוא חיוני, אוהב כולם ומחסן במלואו.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584344/pets/golder-retriever-puppy_kmb7bs.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "Siberian Husky",
    name: "לונה",
    adoptionStatus: "Available",
    height: 55,
    weight: 22,
    color: "Gray and White",
    bio: "לונה היא האסקי סיבירי מרהיב שאוהב מזג אוויר קר ואנרגיה. היא חברותית, דברנית ואוהבת לרוץ.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584344/pets/322868_1100-800x825_jaatwa.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "Border Collie",
    name: "מקס",
    adoptionStatus: "Available",
    height: 53,
    weight: 20,
    color: "Black and White",
    bio: "מקס הוא בורדר קולי חכם במיוחד שמצטיין באג'יליטי. הוא זקוק לפעילות יומית ולמשפחה עם ניסיון בגזע.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584344/pets/MBS_DogEvolution_blg_031820_uc9v2m.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "Labrador Retriever",
    name: "באדי",
    adoptionStatus: "Fostered",
    height: 57,
    weight: 30,
    color: "Yellow",
    bio: "באדי הוא לברדור עם לב זהב. הוא נפלא עם ילדים וכלבים אחרים, וכרגע נמצא בבית אומנה.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584344/pets/petting-smiling-dog-gettyimages-1041987488_b4d5lq.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "Beagle",
    name: "צ'רלי",
    adoptionStatus: "Available",
    height: 38,
    weight: 10,
    color: "Tricolor",
    bio: "צ'רלי הוא ביגל סקרן ושובב שאוהב לעקוב אחר ריחות. הוא נהדר עם ילדים וחיות מחמד אחרות.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584343/pets/dog-451643_dsxlbl.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "Dachshund",
    name: "אוסקר",
    adoptionStatus: "Available",
    height: 22,
    weight: 7,
    color: "Tan",
    bio: "אוסקר הוא דכשונד קטן עם אישיות ענקית. הוא אוהב ליטופים על הבטן ולישון בכתמי שמש.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584343/pets/_126418622_gettyimages-175597750-1_mhpaa5.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  // ── categorized-images.json ────────────────────────────────────────────────
  {
    type: "Dog",
    breed: "Australian Shepherd",
    name: "סייג'",
    adoptionStatus: "Available",
    height: 52,
    weight: 23,
    color: "Blue Merle",
    bio: "סייג' הוא רועה אוסטרלי פעיל שאוהב לרדוף ולשחק. הוא נקשר עמוקות למשפחתו ואוהב תרגול יומי.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1678182778/tz3gblh0vjeesk6zfaat.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "French Bulldog",
    name: "מילו",
    adoptionStatus: "Available",
    height: 30,
    weight: 12,
    color: "Brindle",
    bio: "מילו הוא בולדוג צרפתי שאוהב חיי עיר. הוא בעל אנרגיה נמוכה, מתאים לדירה ומת על בני משפחתו.",
    hypoallergenic: "No",
    dietaryRestrictions: "תזונה ללא גלוטן מומלצת",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1678182733/f4dcgpjhlw4m4tepywpc.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "Poodle",
    name: "דייזי",
    adoptionStatus: "Available",
    height: 35,
    weight: 7,
    color: "White",
    bio: "דייזי היא פודל מיניאטורי חכמה במיוחד, היפואלרגנית ומתאימה למשפחות עם אלרגיות. היא אוהבת ללמוד טריקים.",
    hypoallergenic: "Yes",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1678182625/m6jt3sacmqqf1redwnwx.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "Shiba Inu",
    name: "קודה",
    adoptionStatus: "Available",
    height: 38,
    weight: 10,
    color: "Red",
    bio: "קודה הוא שיבה אינו אנרגטי וסקרן שאוהב הרפתקאות בחוץ. הוא נאמן למשפחתו וזקוק לבעלים מנוסים.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1678182576/rt8uv5usvsg5qstcnegn.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "Golden Retriever",
    name: "קופר",
    adoptionStatus: "Available",
    height: 58,
    weight: 30,
    color: "Golden",
    bio: "קופר הוא גולדן רטריבר הידידותי ביותר שתפגשו. הוא אוהב להביא כדור, לשחות ולהתכרבל על הספה.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1678182515/cdeqoz6w178de4n75ejp.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "German Shepherd",
    name: "רקס",
    adoptionStatus: "Available",
    height: 62,
    weight: 32,
    color: "Black and Tan",
    bio: "רקס הוא רועה גרמני נאמן ואמין. הוא מגן טבעי על המשפחה, מצייתן ואוהב פעילות גופנית.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1678182294/fpskhmra2i9yoicy4ofh.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "Boxer",
    name: "זאוס",
    adoptionStatus: "Available",
    height: 58,
    weight: 30,
    color: "Fawn",
    bio: "זאוס הוא בוקסר שמח ופעיל שאוהב לשחק עם ילדים. הוא חברותי, אנרגטי ומסור למשפחתו.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1678182242/gxyhhoiswx1xld9qow0m.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "Cocker Spaniel",
    name: "נועה",
    adoptionStatus: "Available",
    height: 40,
    weight: 13,
    color: "Chocolate",
    bio: "נועה היא קוקר ספנייל עדינה ואוהבת. היא מסתדרת עם כולם ואוהבת לשבת בחיק בעוד אוזניה מלוטפות.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662621523/dmzjwvkxup0knswoflku.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dog",
    breed: "Jack Russell Terrier",
    name: "ספארק",
    adoptionStatus: "Available",
    height: 30,
    weight: 6,
    color: "White with brown patches",
    bio: "ספארק הוא ג'ק ראסל טרייר קטן עם אנרגיה בלתי נדלית. הוא חכם, שובב ואוהב לחפור.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661941154/ykdgatrro5wjohwawmh2.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
];

// ---------------------------------------------------------------------------
// CATS — 10 from pets/ folder + 8 from categorized = 18 total
// ---------------------------------------------------------------------------
const cats = [
  // ── pets/ folder ──────────────────────────────────────────────────────────
  {
    type: "Cat",
    breed: "Domestic Shorthair",
    name: "ביסלי",
    adoptionStatus: "Available",
    height: 25,
    weight: 4,
    color: "Gray and White",
    bio: "ביסלי הוא חתול ביתי נינוח שאוהב לשכב על החלון ולצפות בציפורים. הוא מסתדר עם ילדים ועם חתולים אחרים.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584343/pets/file-20220131-15-1ndq1m6.jpg_a36xcl.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Tabby Mix",
    name: "קליאו",
    adoptionStatus: "Fostered",
    height: 25,
    weight: 3.5,
    color: "Gray Tabby",
    bio: "קליאו היא חתולת טאבי סקרנית וחיבה שאוהבת לחקור כל פינה בבית. כרגע בבית אומנה.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584342/pets/cats-8-jewish-facts-730_x_411_wvrflk.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Bengal Mix",
    name: "זפיר",
    adoptionStatus: "Available",
    height: 28,
    weight: 5,
    color: "Spotted Brown",
    bio: "זפיר הוא חתול בנגל בעל מראה פרוע ואישיות אנרגטית. הוא אוהב מסיות ציד ופיד פאזלים.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584342/pets/5aa10ca0d877e618008b4678_dw6xh2.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Bombay",
    name: "צל",
    adoptionStatus: "Available",
    height: 24,
    weight: 4,
    color: "Black",
    bio: "צל הוא חתול בומביי שחור כולו עם עיניים זהובות. הוא חיבה, משחקי ומביא רק מזל טוב לביתו.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584342/pets/cat-black-superstitious-fcs-cat-myths-162286659_xpcij5.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Siamese Mix",
    name: "לונה",
    adoptionStatus: "Available",
    height: 25,
    weight: 3.8,
    color: "Cream with dark points",
    bio: "לונה היא חתולת סיאמי דברנית שמשגשגת תשומת לב אנושית. היא תעקוב אחריך מחדר לחדר וממש תנהל שיחה.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584342/pets/shutterstock_1834094695_alf4cq.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Domestic Shorthair",
    name: "ויסקרס",
    adoptionStatus: "Available",
    height: 25,
    weight: 4,
    color: "Orange Tabby",
    bio: "ויסקרס הוא חתול ביתי כתום נינוח שאוהב לשכב בכתמי שמש. הוא מסתדר עם חתולים אחרים וילדים רגועים.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584342/pets/cat-217679_c9e2xz.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Norwegian Forest Cat",
    name: "ברוש",
    adoptionStatus: "Available",
    height: 30,
    weight: 6,
    color: "White and Gray",
    bio: "ברוש הוא חתול יער נורווגי גדול ופרוותי עם אישיות רגועה. הוא אוהב לטפס ולישון בגבהים.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584342/pets/bbac0ea6-6355-4f3d-99e7-77208be2189c_16x9_1200x676.PNG_xod5yy.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Domestic Longhair",
    name: "ג'ינג'ר",
    adoptionStatus: "Available",
    height: 26,
    weight: 4.5,
    color: "Ginger",
    bio: "ג'ינג'ר היא חתולה שעירה אדמונית שאוהבת הברשה. היא רגועה, חיבה ומתאימה לבית שקט.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584340/pets/FELV-cat_ozb7ba.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Tabby",
    name: "מוצ'י",
    adoptionStatus: "Available",
    height: 24,
    weight: 3.8,
    color: "Brown Tabby",
    bio: "מוצ'י הוא חתול טאבי חברותי שמגרגר בקול ואוהב לשבת על המקלדת. הוא יעקוב אחריך מחדר לחדר.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584340/pets/Domestic-feline-tabby-cat.jpg_xyme50.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Persian Mix",
    name: "פנינה",
    adoptionStatus: "Available",
    height: 24,
    weight: 4.2,
    color: "White",
    bio: "פנינה היא חתולת פרסי לבנה ורגועה שאוהבת חיבוקים עדינים. היא מועדפת לסביבה שקטה ובית ללא רעש.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661584340/pets/iStock-1199279669.jpg_bxtq9h.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  // ── categorized-images.json ────────────────────────────────────────────────
  {
    type: "Cat",
    breed: "Ragdoll",
    name: "שמיים",
    adoptionStatus: "Available",
    height: 28,
    weight: 6,
    color: "Blue Point",
    bio: "שמיים הוא חתול רגדול ענקי ורך שנופל לידיים בחיבוק. הוא שקט, עדין ומתאים מאוד למשפחות.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1678183083/icyb49xteckzgwmywzma.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Abyssinian",
    name: "ניל",
    adoptionStatus: "Available",
    height: 26,
    weight: 4.5,
    color: "Ruddy Brown",
    bio: "ניל הוא חתול אביסיניאני פעיל וסקרן שאוהב לחקור. הוא חכם, זריז ומשתובב מאוד.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1678182943/trixo4v2yyhbbcayfv6w.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Scottish Fold",
    name: "אינבר",
    adoptionStatus: "Available",
    height: 24,
    weight: 4.3,
    color: "Gray",
    bio: "אינבר היא חתולת סקוטיש פולד עם אוזניים מקופלות מקסימות. היא רגועה, מצחיקה ומסתגלת לכל בית.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1678182897/wrnu3mzzqk2yvtj1ldgc.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Maine Coon",
    name: "גיא",
    adoptionStatus: "Available",
    height: 32,
    weight: 7,
    color: "Brown Tabby",
    bio: "גיא הוא חתול מיין קון ענקי עם פרווה מרשימה. הוא ידידותי כמו כלב, אוהב מים ומשחק.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1678182852/bhsscgj2xaoz5iwiejj8.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Sphynx",
    name: "פיניקס",
    adoptionStatus: "Available",
    height: 25,
    weight: 4,
    color: "Hairless Pink",
    bio: "פיניקס הוא חתול ספינקס ללא שיער שמחפש חום ואהבה. הוא היפואלרגני, חברותי ויישב לידך כל הזמן.",
    hypoallergenic: "Yes",
    dietaryRestrictions: "תזונה קלורית גבוהה לשמירת חום גוף",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662627100/f8x2cax9mktc8lcsl0vf.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "British Shorthair",
    name: "אטלס",
    adoptionStatus: "Available",
    height: 27,
    weight: 5.5,
    color: "Blue-Gray",
    bio: "אטלס הוא בריטיש שורטהייר עגלגל ושקט. הוא עצמאי אך חיבה, ומסתגל מצוין לדירה.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662559392/ckyk3thmvrn3ke5fcjke.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Turkish Angora",
    name: "שלג",
    adoptionStatus: "Available",
    height: 26,
    weight: 4,
    color: "White",
    bio: "שלג הוא חתול אנגורה טורקי לבן עם עיניים תכולות. הוא חכם, פעיל ואוהב לשחק עם צעצועים.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661941401/wo7ucgcdf41xgetusws4.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Cat",
    breed: "Russian Blue",
    name: "אפוד",
    adoptionStatus: "Fostered",
    height: 25,
    weight: 4,
    color: "Blue-Gray",
    bio: "אפוד הוא חתול רוסי כחול ביישן בתחילה אך נאמן ורגיש לבעליו. הוא שקט ומתאים לבית שקט.",
    hypoallergenic: "No",
    dietaryRestrictions: "ללא הגבלות",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661585356/khqpq8koham81ilmg8tp.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
];

// ---------------------------------------------------------------------------
// HORSES — 9 entries
// ---------------------------------------------------------------------------
const horses = [
  {
    type: "Horse",
    breed: "Icelandic Horse",
    name: "פריה",
    adoptionStatus: "Available",
    height: 140,
    weight: 380,
    color: "Chestnut",
    bio: "פריה היא סוסת איסלנד טהורה, מוכרת בהליכת הטולט הייחודית שלה. היא עדינה, בטוחה ברגליים ומושלמת לרכיבת שטח.",
    hypoallergenic: "No",
    dietaryRestrictions: "שחת ותבואה, ללא פינוקים מתוקים",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661687309/ih8dtskdsthcn7n4w1pj.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Horse",
    breed: "Arabian",
    name: "זרא",
    adoptionStatus: "Available",
    height: 152,
    weight: 450,
    color: "Gray",
    bio: "זרא היא סוסה ערבית אלגנטית עם עיניים חכמות וסבולת מדהימה. היא נקשרת עמוקות לרוכבת שלה.",
    hypoallergenic: "No",
    dietaryRestrictions: "עשבייה עשירה בסיבים, ללא מרעה עשיר",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661687234/nqtwndiqqvdxffj07ae9.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Horse",
    breed: "Thoroughbred",
    name: "ברק",
    adoptionStatus: "Available",
    height: 163,
    weight: 550,
    color: "Bay",
    bio: "ברק הוא סוס תורובד בדימוס שמחפש בית אוהב. הוא עצבני מעט אך מגיב יפה למאמנים מנוסים.",
    hypoallergenic: "No",
    dietaryRestrictions: "מזון ביצועים עם תוספי מפרקים",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661687105/naxxa9lipqtbx22cfypx.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Horse",
    breed: "Quarter Horse",
    name: "דיוק",
    adoptionStatus: "Fostered",
    height: 155,
    weight: 500,
    color: "Palomino",
    bio: "דיוק הוא קווורטר הורס רגוע ומאולף לרכיבה מערבית. מתאים למתחילים וכרגע בבית אומנה.",
    hypoallergenic: "No",
    dietaryRestrictions: "שחת, תבואה מוגבלת",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661686937/lnrib6cjlsxh53yjkzcd.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Horse",
    breed: "Appaloosa",
    name: "נקוד",
    adoptionStatus: "Available",
    height: 150,
    weight: 480,
    color: "Spotted White and Brown",
    bio: "נקוד הוא אפלוסה בעל פרווה מנוקדת מרהיבה. הוא ידידותי, בטוח לשבילים וכיפי עם ילדים.",
    hypoallergenic: "No",
    dietaryRestrictions: "תזונה דלת סוכר, ללא מרעה עשיר",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661686096/vxrmlzyylgrtjcxilzw4.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Horse",
    breed: "Andalusian",
    name: "קפיטן",
    adoptionStatus: "Available",
    height: 158,
    weight: 510,
    color: "White",
    bio: "קפיטן הוא אנדלוסי מפואר מאומן לדרסאז' קלאסי. הוא נמרץ אך קשוב, ומושך עיניים בכל תחרות.",
    hypoallergenic: "No",
    dietaryRestrictions: "שחת איכותי, מוצ'לי, ויטמינים",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661686359/ar7dit8wsenjmmgs2nf5.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Horse",
    breed: "Morgan",
    name: "ריו",
    adoptionStatus: "Available",
    height: 148,
    weight: 460,
    color: "Dark Brown",
    bio: "ריו הוא סוס מורגן ורסטילי המצטיין הן ברכיבה אנגלית והן מערבית. הוא קל לטיפול וחרוץ.",
    hypoallergenic: "No",
    dietaryRestrictions: "שחת בלבד עם גישה לאבן מלח",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661686785/xqz1otqfphriedv8iesn.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Horse",
    breed: "Paint Horse",
    name: "נוקס",
    adoptionStatus: "Available",
    height: 153,
    weight: 490,
    color: "Black and White Pinto",
    bio: "נוקס הוא פיינט הורס מרהיב בצבעי שחור ולבן. הוא מאולף לשבילים ולבידור ובעל אופי נפלא.",
    hypoallergenic: "No",
    dietaryRestrictions: "שחת מעורב עם תוסף ויטמינים",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661685736/pmkizbv4opsprjpv3z5i.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Horse",
    breed: "Friesian",
    name: "ליל",
    adoptionStatus: "Available",
    height: 162,
    weight: 590,
    color: "Black",
    bio: "ליל הוא פריזיאן שחור מרהיב עם רעמה ארוכה. הוא ענק עדין, מתאים לרכיבת עונג ולרתימה.",
    hypoallergenic: "No",
    dietaryRestrictions: "שחת איכותי, תבואה מוגבלת למניעת השמנה",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1661683457/ube8s3hvobobrbqqgjec.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
];

// ---------------------------------------------------------------------------
// TIGERS — 5 entries
// ---------------------------------------------------------------------------
const tigers = [
  {
    type: "Tiger",
    breed: "Bengal Tiger",
    name: "ראג'ה",
    adoptionStatus: "Available",
    height: 110,
    weight: 230,
    color: "Orange with black stripes",
    bio: "ראג'ה הוא נמר בנגל מפואר שחולץ ממתקן גידול בלתי חוקי. הוא גר במתחם מקלט גדול וזקוק לטיפול מומחה.",
    hypoallergenic: "No",
    dietaryRestrictions: "בשר נא, 6–8 ק\"ג ליום",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662549373/vn6rfcaegxdnhpg8uvma.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Tiger",
    breed: "Siberian Tiger",
    name: "איבן",
    adoptionStatus: "Available",
    height: 120,
    weight: 300,
    color: "Pale orange with widely spaced stripes",
    bio: "איבן הוא נמר סיבירי — התת-מין הגדול ביותר. הוא רגוע יחסית ומשגשג במתחם הפתוח שלנו.",
    hypoallergenic: "No",
    dietaryRestrictions: "בשר נא, 8–10 ק\"ג ליום",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662549465/po95shrc7ob342vvitkb.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Tiger",
    breed: "Sumatran Tiger",
    name: "בָּיוּ",
    adoptionStatus: "Fostered",
    height: 90,
    weight: 140,
    color: "Deep orange with thick black stripes",
    bio: "ביו הוא נמר סומטרה — התת-מין הנדיר ביותר. הוא חלק מתוכנית חסות לשמירת המין.",
    hypoallergenic: "No",
    dietaryRestrictions: "בשר נא, 4–6 ק\"ג ליום",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662549551/ozyr7wrl3puwvafjcxwt.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Tiger",
    breed: "Indochinese Tiger",
    name: "נָרָה",
    adoptionStatus: "Available",
    height: 95,
    weight: 175,
    color: "Dark orange with closely spaced stripes",
    bio: "נרה היא נמרה אינדו-סינית נדירה שנולדה בשבי. היא חלק מתוכנית רבייה בינלאומית לשמירת המין.",
    hypoallergenic: "No",
    dietaryRestrictions: "בשר נא, 5–7 ק\"ג ליום",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662549222/i1leqwrlencqgkjpipl3.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Tiger",
    breed: "Bengal Tiger",
    name: "זָרָה",
    adoptionStatus: "Available",
    height: 100,
    weight: 160,
    color: "Golden with black stripes",
    bio: "זרה היא נמרת בנגל צעירה שחולצה מאזור שנחרב. היא חלק מתוכנית הרבייה לשמירת המין.",
    hypoallergenic: "No",
    dietaryRestrictions: "בשר נא, 5–7 ק\"ג ליום",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662548921/ec4qz8oqa6jjdmkbwlxf.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
];

// ---------------------------------------------------------------------------
// DOLPHINS — 10 entries
// ---------------------------------------------------------------------------
const dolphins = [
  {
    type: "Dolphin",
    breed: "Atlantic Spotted Dolphin",
    name: "נקודה",
    adoptionStatus: "Available",
    height: 180,
    weight: 130,
    color: "Gray with white spots",
    bio: "נקודה היא דולפין מנוקד מהאוקיינוס האטלנטי שאוהבת לגלוש על גלי הסירות. חלק מתוכנית החסות הימית שלנו.",
    hypoallergenic: "No",
    dietaryRestrictions: "דגים טריים — הרינג, מקרל ודיונון",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662574968/xra3jmzyhbj1j36wa7i6.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dolphin",
    breed: "Dusky Dolphin",
    name: "דאש",
    adoptionStatus: "Available",
    height: 170,
    weight: 80,
    color: "Dark gray and cream",
    bio: "דאש הוא דולפין אקרובטי מפורסם בקפיצותיו המרהיבות. הוא חברותי מאוד ונוסע בלהקות גדולות בטבע.",
    hypoallergenic: "No",
    dietaryRestrictions: "דגים טריים — אנשובי, דיונון ואגויה",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662559042/ldnqwfqoihj6znlvlgoq.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dolphin",
    breed: "Bottlenose Dolphin",
    name: "פין",
    adoptionStatus: "Available",
    height: 250,
    weight: 200,
    color: "Light gray",
    bio: "פין הוא דולפין אף-בקבוק חברותי ועליז. הוא משתתף בתוכניות חינוך ציבוריות ואוהב להופיע.",
    hypoallergenic: "No",
    dietaryRestrictions: "דגים טריים — מולט, פינפיש ודיונון",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662558939/q7qt308nm6jzk1s1f009.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dolphin",
    breed: "Irrawaddy Dolphin",
    name: "מומו",
    adoptionStatus: "Fostered",
    height: 200,
    weight: 130,
    color: "Blue-gray",
    bio: "מומו היא דולפינת איראוואדי נדירה שחולצה מרשת דיג בדרום-מזרח אסיה. היא בלגונה מוגנת בחסות.",
    hypoallergenic: "No",
    dietaryRestrictions: "דגים טריים — קרפיון, חום ים ושרימפס",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662558811/jmu8uuockceyngirc9cl.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dolphin",
    breed: "Spinner Dolphin",
    name: "סבבי",
    adoptionStatus: "Available",
    height: 190,
    weight: 75,
    color: "Tricolor — dark gray, light gray, and white",
    bio: "סבבי הוא דולפין ספינר מפורסם בסיבובי האוויר שלו. הוא סקרן, מהיר ואוהב לגלוש בעקבות סירות.",
    hypoallergenic: "No",
    dietaryRestrictions: "דגים טריים — פנסונים, דיונון ושרימפס",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662557755/gbfgkuik1hsw7cmnftgl.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dolphin",
    breed: "Striped Dolphin",
    name: "פס",
    adoptionStatus: "Available",
    height: 240,
    weight: 160,
    color: "Blue-gray with white stripes",
    bio: "פס הוא דולפין מפוספס מהיר וזריז שאוהב צלילות עמוקות. הוא חי בים הפתוח וחלק מתוכנית אימוץ.",
    hypoallergenic: "No",
    dietaryRestrictions: "דגים טריים — פנסונים, בקלה ודיונון",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662557957/kq5tsfeb4gqzmfcmixah.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dolphin",
    breed: "Common Dolphin",
    name: "זיפי",
    adoptionStatus: "Available",
    height: 220,
    weight: 110,
    color: "Yellow and gray hourglass pattern",
    bio: "זיפי הוא דולפין נפוץ בעל מהירות מרהיבה. הוא חברותי מאוד, נוסע בלהקות ענק ואוהב לגלוש.",
    hypoallergenic: "No",
    dietaryRestrictions: "דגים טריים — סרדינים, אנשובי ודיונון",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662558270/fzis1qfavmrxjzyoru83.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dolphin",
    breed: "Orca",
    name: "קאי",
    adoptionStatus: "Available",
    height: 600,
    weight: 5500,
    color: "Black and white",
    bio: "קאי הוא אורקה — הדולפין הגדול ביותר. הוא גר במתחם ימי עמוק ולוקח חלק בתוכניות חינוך ציבוריות.",
    hypoallergenic: "No",
    dietaryRestrictions: "דגים, דיונון ויונקי ים — 150–300 ק\"ג ביום",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662555833/dkfmnc5coa8f0m1ifcmq.webp",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dolphin",
    breed: "Pacific White-sided Dolphin",
    name: "גלים",
    adoptionStatus: "Available",
    height: 210,
    weight: 150,
    color: "Black, white, and light gray",
    bio: "גלים הוא דולפין לבן-צד מהפסיפיק האוהב לגלוש בגלים. הוא פעיל, שמח ומגיב היטב לאנשים.",
    hypoallergenic: "No",
    dietaryRestrictions: "דגים טריים — הרינג, לנצטפיש ודיונון",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662550109/glvljwdv25rg176l9tsq.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
  {
    type: "Dolphin",
    breed: "Risso's Dolphin",
    name: "צלקת",
    adoptionStatus: "Available",
    height: 300,
    weight: 500,
    color: "Light gray with white scars",
    bio: "צלקת הוא דולפין ריסו מרשים עם סימני צלקות לבנות מניסיון חיים עשיר. הוא שקט ועמוק-טבילה.",
    hypoallergenic: "No",
    dietaryRestrictions: "דיונון בעיקר, ואוקטופוס",
    imageUrl: "https://res.cloudinary.com/dcvwxiaaz/image/upload/v1662549847/cjbqv1420olpyx9zpzsy.jpg",
    adopt: [],
    foster: [],
    userId: "",
  },
];

// ---------------------------------------------------------------------------
// All pets combined
// ---------------------------------------------------------------------------
const pets = [...dogs, ...cats, ...horses, ...tigers, ...dolphins];

// ---------------------------------------------------------------------------
// Users — 2 admins, 3 regular
// ---------------------------------------------------------------------------
const rawUsers = [
  {
    firstName: "Admin",
    lastName: "ראשי",
    email: "admin@petadoption.com",
    password: "Admin1234!",
    phoneNumber: "0501234567",
    bio: "מנהל המערכת הראשי. אחראי על כל החיות והמשתמשים.",
    isAdmin: true,
    savedPet: [],
    adoptPet: [],
    fosterPet: [],
  },
  {
    firstName: "שניר",
    lastName: "יולזרי",
    email: "snir@petadoption.com",
    password: "Snir1234!",
    phoneNumber: "0509876543",
    bio: "מנהל בכיר ובעלים של הפלטפורמה.",
    isAdmin: true,
    savedPet: [],
    adoptPet: [],
    fosterPet: [],
  },
  {
    firstName: "שרה",
    lastName: "כהן",
    email: "sarah@example.com",
    password: "Sarah1234!",
    phoneNumber: "0521234568",
    bio: "אוהבת בעלי חיים ואמא גאה לכלב. מחפשת לאמץ גם חתול.",
    isAdmin: false,
    savedPet: [],
    adoptPet: [],
    fosterPet: [],
  },
  {
    firstName: "דוד",
    lastName: "לוי",
    email: "david@example.com",
    password: "David1234!",
    phoneNumber: "0541234569",
    bio: "חובב טבע ותיירות. מחפש לאמץ כלב גדול לטיולים.",
    isAdmin: false,
    savedPet: [],
    adoptPet: [],
    fosterPet: [],
  },
  {
    firstName: "מאיה",
    lastName: "מזרחי",
    email: "maya@example.com",
    password: "Maya1234!",
    phoneNumber: "0521112233",
    bio: "סטודנטית לביולוגיה ימית. חולמת לחסות דולפין ולאמץ חתול.",
    isAdmin: false,
    savedPet: [],
    adoptPet: [],
    fosterPet: [],
  },
];

// ---------------------------------------------------------------------------
// Seed
// ---------------------------------------------------------------------------
async function seed() {
  await mongoose.connect(MONGO_URI, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });
  console.log("Connected to MongoDB.");

  await Pets.deleteMany({});
  await User.deleteMany({});
  console.log("Cleared existing pets and users.");

  const users = await Promise.all(
    rawUsers.map(async (u) => ({ ...u, password: await bcrypt.hash(u.password, 10) }))
  );
  await User.insertMany(users);
  console.log(`Inserted ${users.length} users (2 admins, 3 regular).`);

  await Pets.insertMany(pets);

  const counts = pets.reduce((acc, p) => {
    acc[p.type] = (acc[p.type] || 0) + 1;
    return acc;
  }, {});
  console.log(`Inserted ${pets.length} pets:`);
  Object.entries(counts).forEach(([type, n]) => console.log(`  ${type}: ${n}`));

  await mongoose.disconnect();
  console.log("Done. Database seeded successfully.");
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  mongoose.disconnect();
  process.exit(1);
});
